# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'ArticleId')),
                ('title', models.CharField(max_length=100, verbose_name=b'ArticleTitle')),
                ('content', models.TextField(verbose_name=b'ArticleContent')),
                ('date', models.DateField(verbose_name=b'ArticleDate')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'AuthorId')),
                ('name', models.CharField(max_length=20, verbose_name=b'AuthorName')),
                ('sex', models.BooleanField(verbose_name=b'AuthorSex')),
            ],
        ),
    ]
