# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('reading_times', models.IntegerField(auto_created=True, default=0, verbose_name=b'ReadingTimes')),
                ('modify_date', models.DateField(auto_created=True, verbose_name=b'ArticleModifyDate')),
                ('create_date', models.DateField(auto_created=True, verbose_name=b'ArticleCreateDate')),
                ('article_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name=b'ArticleId')),
                ('title', models.CharField(max_length=100, verbose_name=b'ArticleTitle')),
                ('content', models.TextField(verbose_name=b'ArticleContent')),
                ('abstract', models.TextField(max_length=250, verbose_name=b'ArticleAbstract')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(auto_created=True, verbose_name=b'BlockId')),
                ('name', models.CharField(max_length=100, verbose_name=b'BlockName')),
                ('desc', models.CharField(max_length=100, verbose_name=b'BlockDesc')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Block'),
        ),
    ]
